
module.exports = {
	MAPICS_SUPPLIERAZURE_QUERY: function () {
		return "SELECT vend.VNDNR, vend.VNAME, vend.VADD1, vend.VADD2, vend.VCITY, vend.VSTAC, vend.VCNTR, vend.VZIPC from AMFLIBL.VENNAM AS vend INNER JOIN MSSTQACEYK.MXAPGI002 ON MSSTQACEYK.MXAPGI002.VNDNR = vend.VNDNR where MSSTQACEYK.MXAPGI002.PRCSD = 'N' FETCH FIRST 300 ROWS ONLY";
	}
};
